### ISSUE TITLE
Content missing after login with facebook

### ISSUE THREAD

**Issue by samwang0723** [chunchaolee/the-wall#52] opened 2018-04-14 14:30 UTC
When I first launch this page with guest, https://thewall-indiemusic.herokuapp.com/events/350 shows all the details information and ticket price, but after sign up with facebook, all the information gone.

**Comment by chunchaolee** [comment] 2018-04-15 09:31
Hi Sam,
Event which has been over will be destroyed in the every morning. After you login with facebook, the event already destroyed by system. Content or event missing seems like caused by this reason.

**Comment by LanceRabbit** [comment] 2018-04-16 00:14
fixed by @chunchaolee : Content missing after login

**Closed by LanceRabbit** 2018-04-16 00:14 UTC
